"use client";
import { useState } from "react";
import {
  TextInput,
  Code,
  UnstyledButton,
  Text,
  SegmentedControl,
  rem,
  Checkbox,
  ScrollArea,
} from "@mantine/core";
import { IconSearch } from "@tabler/icons-react";
import classes from "./NavbarSearch.module.css";

const tabs = {
  myItems: [
    {
      rgno: "20315",
      season: "Autumn",
      ay: "2023",
      no: "GES054",
      cno: null,
      lang: "E",
      section: null,
      e: "S2: The World of Language Interpreters ",
      j: "Ｓ２: 通訳の世界",
      schedule: "5/TH,6/TH,7/TH",
      room: null,
      comment: null,
      maxnum: "(150)",
      flg: "Face to Face",
      instructor: "TAMURA, Tomoko",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "20316",
      season: "Autumn",
      ay: "2023",
      no: "GES055",
      cno: null,
      lang: "E",
      section: null,
      e: "S2: Language documentation and linguistics ",
      j: "Ｓ２：言語記録と言語学",
      schedule: "1/TU,2/TU,1/TH",
      room: null,
      comment: null,
      maxnum: "(150)",
      flg: "Face to Face",
      instructor: "LEE, Seunghun",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31188",
      season: "Winter",
      ay: "2023",
      no: "ENV301",
      cno: null,
      lang: "J",
      section: null,
      e: "Environmental Conservation ",
      j: "環境保全",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TOBAI, Sadayosi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31189",
      season: "Winter",
      ay: "2023",
      no: "ENV302",
      cno: null,
      lang: "J",
      section: null,
      e: "Environmental Toxicology ",
      j: "環境毒性学",
      schedule: "3/M,3/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "FUJINUMA, Ryosuke/NUNOSHIBA, Tatsuo",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31190",
      season: "Winter",
      ay: "2023",
      no: "GSS201",
      cno: null,
      lang: "E",
      section: null,
      e: "Gender and International Relations ",
      j: "ジェンダーと国際関係",
      schedule: "2/M,2/W,2/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TAKAMATSU, Kana",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31191",
      season: "Winter",
      ay: "2023",
      no: "HST106",
      cno: null,
      lang: "E",
      section: null,
      e: "History of Japan (Modern) III ",
      j: "日本史（近代）III",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "BORLAND, Janet Lorraine",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31192",
      season: "Winter",
      ay: "2023",
      no: "HST222",
      cno: null,
      lang: "E",
      section: null,
      e: "History of Japan in Asia ",
      j: "日本対外交流史",
      schedule: "*4/TU,*4/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "OLAH, Csaba",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31193",
      season: "Winter",
      ay: "2023",
      no: "HST224",
      cno: null,
      lang: "E",
      section: null,
      e: "Modern Japan and ICU ",
      j: "近代日本とICU",
      schedule: "5/TU,6/TU,7/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KISHI, Yu",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31194",
      season: "Winter",
      ay: "2023",
      no: "HST226",
      cno: null,
      lang: "J",
      section: null,
      e: "Introductory Readings in Early Modern Japanese History ",
      j: "近世日本史文献基礎講読",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TSUBAKIDA, Yukiko",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31195",
      season: "Winter",
      ay: "2023",
      no: "HST228",
      cno: null,
      lang: "E",
      section: null,
      e: "Introductory Readings in Contemporary Japanese History ",
      j: "現代日本史文献基礎講読",
      schedule: "1/TU,2/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "BORLAND, Janet Lorraine",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31196",
      season: "Winter",
      ay: "2023",
      no: "HST234",
      cno: null,
      lang: "J",
      section: null,
      e: "History of Southeast Asia ",
      j: "東南アジア史",
      schedule: "5/F,6/F,7/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "NEMOTO, Kei",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31197",
      season: "Winter",
      ay: "2023",
      no: "HST235",
      cno: null,
      lang: "J",
      section: null,
      e: "History of the Middle East ",
      j: "中東史",
      schedule: "5/TU,6/TU,7/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TSUJI, Asuka",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31198",
      season: "Winter",
      ay: "2023",
      no: "HST239",
      cno: null,
      lang: "J",
      section: null,
      e: "Introductory Readings in Modern East Asian History ",
      j: "近代東アジア史文献基礎講読",
      schedule: "5/W,6/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KIKUCHI, Hideaki",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31199",
      season: "Winter",
      ay: "2023",
      no: "HST242",
      cno: null,
      lang: "J",
      section: null,
      e: "Economic History of Europe ",
      j: "ヨーロッパ経済史",
      schedule: "5/M,6/M,7/M",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KONISHI, Emi",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31200",
      season: "Winter",
      ay: "2023",
      no: "HST321",
      cno: null,
      lang: "J",
      section: null,
      e: "Colloquium in Medieval Japanese History ",
      j: "中世日本史特別研究",
      schedule: "5/M,6/M,7/M",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "OLAH, Csaba",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31201",
      season: "Winter",
      ay: "2023",
      no: "HST342",
      cno: null,
      lang: "J",
      section: null,
      e: "Colloquium in European History II ",
      j: "西洋史特別研究 II",
      schedule: "5/F,6/F,7/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "YAMAMOTO, Taeko",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31202",
      season: "Winter",
      ay: "2023",
      no: "IRL103",
      cno: null,
      lang: "E",
      section: null,
      e: "Japan's International Relations ",
      j: "日本の国際関係",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "VOSSE, Wilhelm M.",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31203",
      season: "Winter",
      ay: "2023",
      Label1: "[change]",
      no: "IRL220",
      cno: null,
      lang: "J",
      section: null,
      e: "Global Civil Society ",
      j: "地球市民社会論",
      schedule: "2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "MORI, Katsuhiko",
      unit: "2",
      deleted: "true",
    },
    {
      rgno: "31204",
      season: "Winter",
      ay: "2023",
      no: "IRL236",
      cno: null,
      lang: "E",
      section: null,
      e: "Politics and International Relations in Korea ",
      j: "朝鮮半島の政治と国際関係",
      schedule: "5/W,6/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SUH, Jae-Jung",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31205",
      season: "Winter",
      ay: "2023",
      no: "IRL239",
      cno: null,
      lang: "E",
      section: null,
      e: "Politics and International Relations in the Middle East ",
      j: "中東の政治と国際関係",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "IKEDA, Akifumi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31206",
      season: "Winter",
      ay: "2023",
      no: "IRL311",
      cno: null,
      lang: "J",
      section: null,
      e: "Global Environment and Sustainable Development ",
      j: "地球環境と持続可能な開発",
      schedule: "1/TU,2/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "MORI, Katsuhiko",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31207",
      season: "Winter",
      ay: "2023",
      no: "IRL381",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in International Security ",
      j: "国際安全保障特別研究",
      schedule: "4/W,5/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "VOSSE, Wilhelm M.",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31208",
      season: "Winter",
      ay: "2023",
      no: "IRL385",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in Human Security ",
      j: "人間の安全保障特別研究",
      schedule: "6/TH,7/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SHANI, Giorgiandrea",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31209",
      season: "Winter",
      ay: "2023",
      no: "IRL388",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in International Relations ",
      j: "国際関係学特別研究",
      schedule: "5/TH,6/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SALTON, Herman",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31210",
      season: "Winter",
      ay: "2023",
      Label1: "[change]",
      no: "ISC102",
      cno: null,
      lang: "J",
      section: null,
      e: "Elements of Discrete Mathematics ",
      j: "離散数学基礎",
      schedule: null,
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "TBA",
      unit: "2",
      deleted: "false",
    },
    {
      rgno: "31211",
      season: "Winter",
      ay: "2023",
      no: "ISC106",
      cno: null,
      lang: "J",
      section: null,
      e: "Laboratory in Information Science ",
      j: "情報科学実験",
      schedule: "5/TH,(6/TH,7/TH)",
      room: "I-106",
      comment: null,
      maxnum: "(81)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31212",
      season: "Winter",
      ay: "2023",
      no: "ISC212",
      cno: null,
      lang: "J",
      section: null,
      e: "Information Network Security ",
      j: "情報ネットワークセキュリティー",
      schedule: "5/TH,(6/TH,7/TH)",
      room: "I-206",
      comment: null,
      maxnum: "(50)",
      flg: "Face to Face",
      instructor: "ISHIBASHI, Keisuke",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31213",
      season: "Winter",
      ay: "2023",
      no: "ISC225",
      cno: null,
      lang: "J",
      section: null,
      e: "Data Science Concepts ",
      j: "データサイエンス概念",
      schedule: "5/M,(6/M,7/M)",
      room: "I-206",
      comment: null,
      maxnum: "(50)",
      flg: "Face to Face",
      instructor: "ISHIBASHI, Keisuke",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31214",
      season: "Winter",
      ay: "2023",
      no: "ISC251",
      cno: null,
      lang: "J",
      section: null,
      e: "Multimedia Systems ",
      j: "マルチメディアシステム",
      schedule: "5/M,(6/M,7/M)",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "OHTA, Keiji",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31215",
      season: "Winter",
      ay: "2023",
      no: "ISC313",
      cno: null,
      lang: "E",
      section: null,
      e: "Database Systems ",
      j: "デ一タベ一ス論",
      schedule: "5/TH,6/TH",
      room: null,
      comment: null,
      maxnum: "(150)",
      flg: "Online",
      instructor: "KUTICSNE MATZ, Andrea",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31216",
      season: "Winter",
      ay: "2023",
      no: "ISC315",
      cno: null,
      lang: "J",
      section: null,
      e: "Senior Seminar in Information Science I ",
      j: "情報科学四年次セミナー I",
      schedule: "2/TH,3/TH",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31217",
      season: "Winter",
      ay: "2023",
      no: "ISC342",
      cno: null,
      lang: "J",
      section: null,
      e: "Robotics ",
      j: "ロボット工学",
      schedule: "4/F,5/F,6/F",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31218",
      season: "Winter",
      ay: "2023",
      no: "ISC343",
      cno: null,
      lang: "J",
      section: null,
      e: "Topics in Information Technology ",
      j: "情報技術特論",
      schedule: "4/M,4/W",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "OHTA, Keiji",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31219",
      season: "Winter",
      ay: "2023",
      no: "LED102",
      cno: null,
      lang: "J",
      section: null,
      e: "Principles of Language Learning and Teaching ",
      j: "言語教授法原論",
      schedule: "3/M,3/W,3/F",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "SHIROZA, Saran/TSUJITA, Mari",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31220",
      season: "Winter",
      ay: "2023",
      no: "LED214",
      cno: null,
      lang: "E",
      section: null,
      e: "Pragmatics and Language Learning ",
      j: "言語学習における語用論",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "QUAY, Suzanne",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
  ],
  addNew: [
    {
      rgno: "20316",
      season: "Autumn",
      ay: "2023",
      no: "GES055",
      cno: null,
      lang: "E",
      section: null,
      e: "S2: Language documentation and linguistics ",
      j: "Ｓ２：言語記録と言語学",
      schedule: "1/TU,2/TU,1/TH",
      room: null,
      comment: null,
      maxnum: "(150)",
      flg: "Face to Face",
      instructor: "LEE, Seunghun",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31188",
      season: "Winter",
      ay: "2023",
      no: "ENV301",
      cno: null,
      lang: "J",
      section: null,
      e: "Environmental Conservation ",
      j: "環境保全",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TOBAI, Sadayosi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31189",
      season: "Winter",
      ay: "2023",
      no: "ENV302",
      cno: null,
      lang: "J",
      section: null,
      e: "Environmental Toxicology ",
      j: "環境毒性学",
      schedule: "3/M,3/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "FUJINUMA, Ryosuke/NUNOSHIBA, Tatsuo",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31190",
      season: "Winter",
      ay: "2023",
      no: "GSS201",
      cno: null,
      lang: "E",
      section: null,
      e: "Gender and International Relations ",
      j: "ジェンダーと国際関係",
      schedule: "2/M,2/W,2/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TAKAMATSU, Kana",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31191",
      season: "Winter",
      ay: "2023",
      no: "HST106",
      cno: null,
      lang: "E",
      section: null,
      e: "History of Japan (Modern) III ",
      j: "日本史（近代）III",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "BORLAND, Janet Lorraine",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31192",
      season: "Winter",
      ay: "2023",
      no: "HST222",
      cno: null,
      lang: "E",
      section: null,
      e: "History of Japan in Asia ",
      j: "日本対外交流史",
      schedule: "*4/TU,*4/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "OLAH, Csaba",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31193",
      season: "Winter",
      ay: "2023",
      no: "HST224",
      cno: null,
      lang: "E",
      section: null,
      e: "Modern Japan and ICU ",
      j: "近代日本とICU",
      schedule: "5/TU,6/TU,7/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KISHI, Yu",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31194",
      season: "Winter",
      ay: "2023",
      no: "HST226",
      cno: null,
      lang: "J",
      section: null,
      e: "Introductory Readings in Early Modern Japanese History ",
      j: "近世日本史文献基礎講読",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TSUBAKIDA, Yukiko",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31195",
      season: "Winter",
      ay: "2023",
      no: "HST228",
      cno: null,
      lang: "E",
      section: null,
      e: "Introductory Readings in Contemporary Japanese History ",
      j: "現代日本史文献基礎講読",
      schedule: "1/TU,2/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "BORLAND, Janet Lorraine",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31196",
      season: "Winter",
      ay: "2023",
      no: "HST234",
      cno: null,
      lang: "J",
      section: null,
      e: "History of Southeast Asia ",
      j: "東南アジア史",
      schedule: "5/F,6/F,7/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "NEMOTO, Kei",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31197",
      season: "Winter",
      ay: "2023",
      no: "HST235",
      cno: null,
      lang: "J",
      section: null,
      e: "History of the Middle East ",
      j: "中東史",
      schedule: "5/TU,6/TU,7/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "TSUJI, Asuka",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31198",
      season: "Winter",
      ay: "2023",
      no: "HST239",
      cno: null,
      lang: "J",
      section: null,
      e: "Introductory Readings in Modern East Asian History ",
      j: "近代東アジア史文献基礎講読",
      schedule: "5/W,6/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KIKUCHI, Hideaki",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31199",
      season: "Winter",
      ay: "2023",
      no: "HST242",
      cno: null,
      lang: "J",
      section: null,
      e: "Economic History of Europe ",
      j: "ヨーロッパ経済史",
      schedule: "5/M,6/M,7/M",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "KONISHI, Emi",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31200",
      season: "Winter",
      ay: "2023",
      no: "HST321",
      cno: null,
      lang: "J",
      section: null,
      e: "Colloquium in Medieval Japanese History ",
      j: "中世日本史特別研究",
      schedule: "5/M,6/M,7/M",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "OLAH, Csaba",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31201",
      season: "Winter",
      ay: "2023",
      no: "HST342",
      cno: null,
      lang: "J",
      section: null,
      e: "Colloquium in European History II ",
      j: "西洋史特別研究 II",
      schedule: "5/F,6/F,7/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "YAMAMOTO, Taeko",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31202",
      season: "Winter",
      ay: "2023",
      no: "IRL103",
      cno: null,
      lang: "E",
      section: null,
      e: "Japan's International Relations ",
      j: "日本の国際関係",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "VOSSE, Wilhelm M.",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31203",
      season: "Winter",
      ay: "2023",
      Label1: "[change]",
      no: "IRL220",
      cno: null,
      lang: "J",
      section: null,
      e: "Global Civil Society ",
      j: "地球市民社会論",
      schedule: "2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "MORI, Katsuhiko",
      unit: "2",
      deleted: "true",
    },
    {
      rgno: "31204",
      season: "Winter",
      ay: "2023",
      no: "IRL236",
      cno: null,
      lang: "E",
      section: null,
      e: "Politics and International Relations in Korea ",
      j: "朝鮮半島の政治と国際関係",
      schedule: "5/W,6/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SUH, Jae-Jung",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31205",
      season: "Winter",
      ay: "2023",
      no: "IRL239",
      cno: null,
      lang: "E",
      section: null,
      e: "Politics and International Relations in the Middle East ",
      j: "中東の政治と国際関係",
      schedule: "5/F,6/F",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "IKEDA, Akifumi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31206",
      season: "Winter",
      ay: "2023",
      no: "IRL311",
      cno: null,
      lang: "J",
      section: null,
      e: "Global Environment and Sustainable Development ",
      j: "地球環境と持続可能な開発",
      schedule: "1/TU,2/TU",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "MORI, Katsuhiko",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31207",
      season: "Winter",
      ay: "2023",
      no: "IRL381",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in International Security ",
      j: "国際安全保障特別研究",
      schedule: "4/W,5/W",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "VOSSE, Wilhelm M.",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31208",
      season: "Winter",
      ay: "2023",
      no: "IRL385",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in Human Security ",
      j: "人間の安全保障特別研究",
      schedule: "6/TH,7/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SHANI, Giorgiandrea",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31209",
      season: "Winter",
      ay: "2023",
      no: "IRL388",
      cno: null,
      lang: "E",
      section: null,
      e: "Advanced Studies in International Relations ",
      j: "国際関係学特別研究",
      schedule: "5/TH,6/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "SALTON, Herman",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31210",
      season: "Winter",
      ay: "2023",
      Label1: "[change]",
      no: "ISC102",
      cno: null,
      lang: "J",
      section: null,
      e: "Elements of Discrete Mathematics ",
      j: "離散数学基礎",
      schedule: null,
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "TBA",
      unit: "2",
      deleted: "false",
    },
    {
      rgno: "31211",
      season: "Winter",
      ay: "2023",
      no: "ISC106",
      cno: null,
      lang: "J",
      section: null,
      e: "Laboratory in Information Science ",
      j: "情報科学実験",
      schedule: "5/TH,(6/TH,7/TH)",
      room: "I-106",
      comment: null,
      maxnum: "(81)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31212",
      season: "Winter",
      ay: "2023",
      no: "ISC212",
      cno: null,
      lang: "J",
      section: null,
      e: "Information Network Security ",
      j: "情報ネットワークセキュリティー",
      schedule: "5/TH,(6/TH,7/TH)",
      room: "I-206",
      comment: null,
      maxnum: "(50)",
      flg: "Face to Face",
      instructor: "ISHIBASHI, Keisuke",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31213",
      season: "Winter",
      ay: "2023",
      no: "ISC225",
      cno: null,
      lang: "J",
      section: null,
      e: "Data Science Concepts ",
      j: "データサイエンス概念",
      schedule: "5/M,(6/M,7/M)",
      room: "I-206",
      comment: null,
      maxnum: "(50)",
      flg: "Face to Face",
      instructor: "ISHIBASHI, Keisuke",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31214",
      season: "Winter",
      ay: "2023",
      no: "ISC251",
      cno: null,
      lang: "J",
      section: null,
      e: "Multimedia Systems ",
      j: "マルチメディアシステム",
      schedule: "5/M,(6/M,7/M)",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "OHTA, Keiji",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31215",
      season: "Winter",
      ay: "2023",
      no: "ISC313",
      cno: null,
      lang: "E",
      section: null,
      e: "Database Systems ",
      j: "デ一タベ一ス論",
      schedule: "5/TH,6/TH",
      room: null,
      comment: null,
      maxnum: "(150)",
      flg: "Online",
      instructor: "KUTICSNE MATZ, Andrea",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31216",
      season: "Winter",
      ay: "2023",
      no: "ISC315",
      cno: null,
      lang: "J",
      section: null,
      e: "Senior Seminar in Information Science I ",
      j: "情報科学四年次セミナー I",
      schedule: "2/TH,3/TH",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31217",
      season: "Winter",
      ay: "2023",
      no: "ISC342",
      cno: null,
      lang: "J",
      section: null,
      e: "Robotics ",
      j: "ロボット工学",
      schedule: "4/F,5/F,6/F",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "KABURAGI, Takashi",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31218",
      season: "Winter",
      ay: "2023",
      no: "ISC343",
      cno: null,
      lang: "J",
      section: null,
      e: "Topics in Information Technology ",
      j: "情報技術特論",
      schedule: "4/M,4/W",
      room: "I-212",
      comment: null,
      maxnum: "(63)",
      flg: "Face to Face",
      instructor: "OHTA, Keiji",
      unit: "2",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31219",
      season: "Winter",
      ay: "2023",
      no: "LED102",
      cno: null,
      lang: "J",
      section: null,
      e: "Principles of Language Learning and Teaching ",
      j: "言語教授法原論",
      schedule: "3/M,3/W,3/F",
      room: null,
      comment: null,
      maxnum: "(180)",
      flg: "Face to Face",
      instructor: "SHIROZA, Saran/TSUJITA, Mari",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
    {
      rgno: "31220",
      season: "Winter",
      ay: "2023",
      no: "LED214",
      cno: null,
      lang: "E",
      section: null,
      e: "Pragmatics and Language Learning ",
      j: "言語学習における語用論",
      schedule: "3/TU,2/TH,3/TH",
      room: null,
      comment: null,
      maxnum: null,
      flg: "Face to Face",
      instructor: "QUAY, Suzanne",
      unit: "3",
      deleted: "false",
      Label1: null,
    },
  ],
};
export function NavbarSearch() {
  const [section, setSection] = useState<"myItems" | "addNew">("myItems");
  const [value, onChange] = useState(false);

  const courses = tabs[section].map((item) => (
    <UnstyledButton
      key={item.e}
      onClick={() => onChange(!value)}
      className={classes.button}
      my={10}
    >
      <Checkbox
        checked={value}
        onChange={() => {}}
        tabIndex={-1}
        size="md"
        mr="xl"
        styles={{ input: { cursor: "pointer" } }}
        aria-hidden
      />

      <div>
        <Text fz="sm" mb={7} lh={1}>
          {item.e}
        </Text>
        <Text fz="sm" c="dimmed">
          {item.instructor}
        </Text>
      </div>
    </UnstyledButton>
  ));

  return (
    <nav className={classes.navbar}>
      <TextInput
        placeholder="Search"
        size="xs"
        leftSection={
          <IconSearch
            style={{ width: rem(12), height: rem(12) }}
            stroke={1.5}
          />
        }
        rightSectionWidth={70}
        rightSection={<Code className={classes.searchCode}>Cmd + K</Code>}
        styles={{ section: { pointerEvents: "none" } }}
        mb="sm"
      />

      <div>
        <SegmentedControl
          value={section}
          onChange={(value: any) => setSection(value)}
          transitionTimingFunction="ease"
          fullWidth
          data={[
            { label: "My List", value: "myItems" },
            { label: "Add New", value: "addNew" },
          ]}
        />
      </div>

      <ScrollArea h={"100vh"}>
        <div className={classes.navbarMain}>{courses}</div>
      </ScrollArea>
    </nav>
  );
}
